language: php

php:
  - 5.3.3
  - 5.3
  - 5.4
  - 5.5

matrix:
  # Use PHP 5.4 for coverage reporting.
  include:
    - php: 5.4
      env:
        - secure: "TSF8gSbWBOvyjq/Cs2Gi+TZabbbgAx/gVHmHGIVNaIxNOnzTX/Q61d1B4/Mw\naLriubvsz2Xn5udWrp031/ZZ4zT6rRi/yD84+EKabSLDDvy/ZFgQbcgucW6K\n/ZuF6NsbeqQnolvVJGdSAsKvd2VC8DO0TVRRRq/2m0zwFx9AqRI="

  # PHP 5.5 is still in alpha, so ignore build failures.
  allow_failures:
    - php: 5.5

install: composer install --dev
script:  ./vendor/bin/travis-build
