var tree = [["Icecave",,"",
                [["Woodhouse","Icecave\/Woodhouse.html","",
                [["BuildStatus","Icecave\/Woodhouse\/BuildStatus.html","",
                [["Readers","Icecave\/Woodhouse\/BuildStatus\/Readers.html","",
                [["CommandLineReader","Icecave\/Woodhouse\/BuildStatus\/Readers\/CommandLineReader.html","",
                [        ]],["JUnitReader","Icecave\/Woodhouse\/BuildStatus\/Readers\/JUnitReader.html","",
                [        ]],["PhpUnitJsonReader","Icecave\/Woodhouse\/BuildStatus\/Readers\/PhpUnitJsonReader.html","",
                [        ]],["TapReader","Icecave\/Woodhouse\/BuildStatus\/Readers\/TapReader.html","",
                [        ]]        ]],["BuildStatus","Icecave\/Woodhouse\/BuildStatus\/BuildStatus.html"," < Enumeration",
                [        ]],["StatusImageSelector","Icecave\/Woodhouse\/BuildStatus\/StatusImageSelector.html","",
                [        ]],["StatusReaderFactory","Icecave\/Woodhouse\/BuildStatus\/StatusReaderFactory.html","",
                [        ]],["StatusReaderInterface","Icecave\/Woodhouse\/BuildStatus\/StatusReaderInterface.html","",
                [        ]]        ]],["Console","Icecave\/Woodhouse\/Console.html","",
                [["Command","Icecave\/Woodhouse\/Console\/Command.html","",
                [["GitHub","Icecave\/Woodhouse\/Console\/Command\/GitHub.html","",
                [["AbstractGitHubCommand","Icecave\/Woodhouse\/Console\/Command\/GitHub\/AbstractGitHubCommand.html"," < Command",
                [        ]],["CreateAuthorizationCommand","Icecave\/Woodhouse\/Console\/Command\/GitHub\/CreateAuthorizationCommand.html"," < AbstractGitHubCommand",
                [        ]],["DeleteAuthorizationCommand","Icecave\/Woodhouse\/Console\/Command\/GitHub\/DeleteAuthorizationCommand.html"," < AbstractGitHubCommand",
                [        ]],["ListAuthorizationsCommand","Icecave\/Woodhouse\/Console\/Command\/GitHub\/ListAuthorizationsCommand.html"," < AbstractGitHubCommand",
                [        ]]        ]],["PublishCommand","Icecave\/Woodhouse\/Console\/Command\/PublishCommand.html"," < Command",
                [        ]]        ]],["Helper","Icecave\/Woodhouse\/Console\/Helper.html","",
                [["HiddenInputHelper","Icecave\/Woodhouse\/Console\/Helper\/HiddenInputHelper.html"," < Helper",
                [        ]]        ]],["Application","Icecave\/Woodhouse\/Console\/Application.html"," < Application",
                [        ]]        ]],["Coverage","Icecave\/Woodhouse\/Coverage.html","",
                [["Readers","Icecave\/Woodhouse\/Coverage\/Readers.html","",
                [["CommandLineReader","Icecave\/Woodhouse\/Coverage\/Readers\/CommandLineReader.html","",
                [        ]],["PhpUnitTextReader","Icecave\/Woodhouse\/Coverage\/Readers\/PhpUnitTextReader.html","",
                [        ]]        ]],["CoverageImageSelector","Icecave\/Woodhouse\/Coverage\/CoverageImageSelector.html","",
                [        ]],["CoverageReaderFactory","Icecave\/Woodhouse\/Coverage\/CoverageReaderFactory.html","",
                [        ]],["CoverageReaderInterface","Icecave\/Woodhouse\/Coverage\/CoverageReaderInterface.html","",
                [        ]]        ]],["Git","Icecave\/Woodhouse\/Git.html","",
                [["Git","Icecave\/Woodhouse\/Git\/Git.html","",
                [        ]]        ]],["GitHub","Icecave\/Woodhouse\/GitHub.html","",
                [["GitHubClient","Icecave\/Woodhouse\/GitHub\/GitHubClient.html","",
                [        ]],["GitHubClientFactory","Icecave\/Woodhouse\/GitHub\/GitHubClientFactory.html","",
                [        ]]        ]],["Publisher","Icecave\/Woodhouse\/Publisher.html","",
                [["AbstractPublisher","Icecave\/Woodhouse\/Publisher\/AbstractPublisher.html","",
                [        ]],["GitHubPublisher","Icecave\/Woodhouse\/Publisher\/GitHubPublisher.html"," < AbstractPublisher",
                [        ]],["PublisherInterface","Icecave\/Woodhouse\/Publisher\/PublisherInterface.html","",
                [        ]]        ]],["PackageInfo","Icecave\/Woodhouse\/PackageInfo.html","",
                [        ]]        ]]        ]]        ]

